version: "3"

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: backend/.
    #    env_file:
    #      - .env
    ports:
      - "8000:8000"
  frontend:
    build:
      dockerfile: Dockerfile
      context: frontend/.
    ports:
      - "3000:3000"