services:
  backend:
    build:
      dockerfile: Dockerfile
      context: backend/.
#    image: markqiu/fastapi-realworld-example-app
#    env_file:
#      - .env
    ports:
      - "8000:8000"
  frontend:
    build:
      dockerfile: Dockerfile
      context: frontend/.
    ports:
      - "3000:3000"
    depends_on:
      - backend
